language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03 PACKAGE=ocsigenserver
  - OCAML_VERSION=4.05 PACKAGE=ocsigenserver
  - OCAML_VERSION=4.06 PACKAGE=ocsigenserver
os:
  - linux
  - osx
jobs:
  include:
    - stage: deploy html_of_wiki
      install: true
      script: ./.howdocgen
      deploy:
        provider: pages
        keep-history: true
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: _doc
        on:
          branch: master
